### ISSUE TITLE
Model Registry not Connecting via the python sdk after installation

### ISSUE THREAD

**Issue by R3hankhan123** [opendatahub-io/model-registry-operator#156]
**Describe the bug**
After following the [steps](https://github.com/opendatahub-io/model-registry-operator/blob/main/docs/install.md) for installing model registry. I am trying to connect to the registry via the python sdk as given in the [docs](https://github.com/opendatahub-io/model-registry-operator/blob/main/docs/python-example-usage.ipynb)
I have written the following code 
```
from model_registry import ModelRegistry

registry = ModelRegistry("https://modelregistry-public-rest.apps.ocpz-standard.a3elp75.lnxero1.boe", author="kube:admin", user_token="token")

# Register a new model
rm = registry.register_model(
    name="mnist",
    uri="https://github.com/tarilabs/demo20231212/raw/main/v1.nb20231206162408/mnist.onnx",
    model_format_name="onnx",
    model_format_version="1",
    version="v0.1",
    description="lorem ipsum mnist",
    metadata={
        "accuracy": 3.14,
        "license": "apache-2.0"
    }
)
print("Registered Model:", rm, "with ID", rm.id)

# Retrieve model details
model = registry.get_registered_model("mnist")
print("Registered Model:", model, "with ID", model.id)

# Retrieve a specific model version
version = registry.get_model_version("mnist", "v0.1")
print("Model Version:", version, "with ID", version.id)

# Retrieve the model artifact
art = registry.get_model_artifact("mnist", "v0.1")
print("Model Artifact:", art, "with ID", art.id)
```
The token here is a placeholder for the actual token gotten using the `oc whoami -t`.
When running the script i am getting the following error
```
[root@ocpz-standard-bastion pip_packages]# python3.9  abc.py 
Traceback (most recent call last):
  File "/usr/local/lib64/python3.9/site-packages/aiohttp/connector.py", line 1097, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1090, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 1120, in _create_connection_transport
    await waiter
  File "/usr/lib64/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib64/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/lib64/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/lib64/python3.9/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/lib64/python3.9/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.9/ssl.py", line 945, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1147)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/pip_packages/abc.py", line 6, in <module>
    rm = registry.register_model(
  File "/usr/local/lib/python3.9/site-packages/model_registry/_client.py", line 173, in register_model
    rm = self.async_runner(self._register_model(name, owner=owner or self._author))
  File "/usr/local/lib/python3.9/site-packages/model_registry/_client.py", line 98, in async_runner
    return loop.run_until_complete(coro)
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/usr/lib64/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/lib64/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/usr/local/lib/python3.9/site-packages/model_registry/_client.py", line 101, in _register_model
    if rm := await self._api.get_registered_model_by_params(name):
  File "/usr/local/lib/python3.9/site-packages/model_registry/core.py", line 156, in get_registered_model_by_params
    rm = await client.find_registered_model(
  File "/usr/local/lib/python3.9/site-packages/mr_openapi/api/model_registry_service_api.py", line 3471, in find_registered_model
    response_data = await self.api_client.call_api(*_param, _request_timeout=_request_timeout)
  File "/usr/local/lib/python3.9/site-packages/mr_openapi/api_client.py", line 231, in call_api
    response_data = await self.rest_client.request(
  File "/usr/local/lib/python3.9/site-packages/mr_openapi/rest.py", line 165, in request
    r = await pool_manager.request(**args)
  File "/usr/local/lib64/python3.9/site-packages/aiohttp/client.py", line 699, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib64/python3.9/site-packages/aiohttp/connector.py", line 562, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib64/python3.9/site-packages/aiohttp/connector.py", line 1031, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib64/python3.9/site-packages/aiohttp/connector.py", line 1375, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib64/python3.9/site-packages/aiohttp/connector.py", line 1344, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib64/python3.9/site-packages/aiohttp/connector.py", line 1099, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host modelregistry-public-rest.apps.ocpz-standard.a3elp75.lnxero1.boe:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1147)')]
```

**To Reproduce**
1. Follow the steps given in the install doc
2. Download the model registry package
3. Run the script 

**Expected behavior**
The script should login to the registry and register the model
**Additional context**
I am using python 3.9.
The url and user are as follows
```
 echo "https://$(oc get routes -n istio-system -l app.kubernetes.io/name=modelregistry-public -o json | jq '.items[].status.ingress[].host | select(contains("-rest"))')" | tr -d '"'
https://modelregistry-public-rest.apps.ocpz-standard.a3elp75.lnxero1.boe
oc whoami
kube:admin
```

**Comment by rareddy** [comment]
the certificates are setup such that the Python client can be used directly without any changes from inside the cluster. i.e. if you are using Jupyter notebook inside the ODH it will correctly. otherwise, you can "issecure=false" option on model registry connection string to see if that works

**Comment by R3hankhan123** [comment]
Unfortunately the same error is coming when using the `is_secure=false' option in the model registry string

**Comment by rareddy** [comment]
is this using inside Jupyter notebook on the same cluster or outside using Jupyter?

**Comment by R3hankhan123** [comment]
I am just uploading the yaml file into the pipelines, the file is generated on my local machine
